Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g43, pull requests merged in 2024-10, with the labels that each got.

#35 Improve Dashboard Page and Others
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/Calendar.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/History.jsx
  frontend/src/components/MonthlyProgress.jsx
  frontend/src/components/ProgressOverview.jsx
  frontend/src/components/Questions.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/Welcome.jsx
  frontend/src/main.jsx
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Help.jsx
  frontend/src/pages/MatchingService.jsx
  frontend/src/pages/PeerPrep.jsx
  frontend/src/pages/Settings.jsx
Labels: enhancement

#37 Add Finding a Peer Page
  frontend/src/main.jsx
  frontend/src/pages/FindingPeer.jsx
  frontend/src/pages/MatchingService.jsx
Labels: enhancement, medium

#40 Add Features and About Page
  dump.rdb
  frontend/src/components/Navbar.jsx
  frontend/src/main.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Features.jsx
Labels: enhancement

#41 Milestone 4
  backend/README.md
  backend/matching-service/.dockerignore
  backend/matching-service/.prettierignore
  backend/matching-service/.prettierrc.json
  backend/matching-service/Dockerfile
  backend/matching-service/controller/redis.js
  backend/matching-service/middleware/basic-access-control.js
  backend/matching-service/package-lock.json
  backend/matching-service/package.json
  backend/matching-service/server.js
  backend/user-service/controller/auth-controller.js
  backend/user-service/controller/user-controller.js
  backend/user-service/index.js
  backend/user-service/middleware/basic-access-control.js
  backend/user-service/model/repository.js
  backend/user-service/model/user-model.js
  backend/user-service/routes/auth-routes.js
  docker-compose.yml
  dump.rdb
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/abik-peravan-unsplash.jpg
  frontend/public/images/man.gif
  frontend/src/App.jsx
  frontend/src/components/Calendar.jsx
  frontend/src/components/Header.jsx
  frontend/src/components/History.jsx
  frontend/src/components/LevelSelect.jsx
  frontend/src/components/LogoutModal.jsx
  frontend/src/components/MonthlyProgress.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/ProgressOverview.jsx
  frontend/src/components/QuestionModal.jsx
  frontend/src/components/Questions.jsx
  frontend/src/components/Sidebar.jsx
  frontend/src/components/TopicSelect.jsx
  frontend/src/components/WaitTimeSelect.jsx
  frontend/src/components/Welcome.jsx
  frontend/src/main.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Dashboard.jsx
  frontend/src/pages/Features.jsx
  frontend/src/pages/FindingPeer.jsx
  frontend/src/pages/Help.jsx
  frontend/src/pages/Login.jsx
  frontend/src/pages/MatchingService.jsx
  frontend/src/pages/PeerPrep.jsx
  frontend/src/pages/ProtectedRoute.jsx
  frontend/src/pages/Room.jsx
  frontend/src/pages/Settings.jsx
  frontend/src/pages/SignUp.jsx
  frontend/src/services/Api.js
  frontend/src/services/MatchingService.js
  frontend/src/services/UserService.js
  frontend/tailwind.config.js
Labels: high
